services:
  qdrant-db:
    image: qdrant/qdrant
    container_name: qdrant-db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gpt-user
      POSTGRES_PASSWORD: gpt-password
      POSTGRES_DB: movies-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend-fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-fast-api
    ports:
      - "8000:8000"
    depends_on:
      - qdrant-db
    environment:
      - QDRANT_URL=http://qdrant-db:6333

  frontend-nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-nextjs
    ports:
      - "3000:3000"
    depends_on:
      - backend-fast-api